//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMIGHT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestFolderPath {
            get {
                return ((string)(this["latestFolderPath"]));
            }
            set {
                this["latestFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestURL {
            get {
                return ((string)(this["latestURL"]));
            }
            set {
                this["latestURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestStockDataColumnNamesStr {
            get {
                return ((string)(this["latestStockDataColumnNamesStr"]));
            }
            set {
                this["latestStockDataColumnNamesStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastestHeaderAndFooterRowCountStr {
            get {
                return ((string)(this["lastestHeaderAndFooterRowCountStr"]));
            }
            set {
                this["lastestHeaderAndFooterRowCountStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestKeyColumnLetter {
            get {
                return ((string)(this["latestKeyColumnLetter"]));
            }
            set {
                this["latestKeyColumnLetter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestExcelWorksheetIndexesStr {
            get {
                return ((string)(this["latestExcelWorksheetIndexesStr"]));
            }
            set {
                this["latestExcelWorksheetIndexesStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestExcelWorksheetName {
            get {
                return ((string)(this["latestExcelWorksheetName"]));
            }
            set {
                this["latestExcelWorksheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestOperatingRangeAddresses {
            get {
                return ((string)(this["latestOperatingRangeAddresses"]));
            }
            set {
                this["latestOperatingRangeAddresses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestKeyDataColumnName {
            get {
                return ((string)(this["latestKeyDataColumnName"]));
            }
            set {
                this["latestKeyDataColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestFontName {
            get {
                return ((string)(this["latestFontName"]));
            }
            set {
                this["latestFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestBatchProcessWorkbookOption {
            get {
                return ((string)(this["latestBatchProcessWorkbookOption"]));
            }
            set {
                this["latestBatchProcessWorkbookOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestSplitWorksheetOption {
            get {
                return ((string)(this["latestSplitWorksheetOption"]));
            }
            set {
                this["latestSplitWorksheetOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string savingFolderPath {
            get {
                return ((string)(this["savingFolderPath"]));
            }
            set {
                this["savingFolderPath"] = value;
            }
        }
    }
}
