//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMIGHT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestFolderPath {
            get {
                return ((string)(this["latestFolderPath"]));
            }
            set {
                this["latestFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestURL {
            get {
                return ((string)(this["latestURL"]));
            }
            set {
                this["latestURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestStockDataColumnNamesStr {
            get {
                return ((string)(this["latestStockDataColumnNamesStr"]));
            }
            set {
                this["latestStockDataColumnNamesStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastestHeaderAndFooterRowCountStr {
            get {
                return ((string)(this["lastestHeaderAndFooterRowCountStr"]));
            }
            set {
                this["lastestHeaderAndFooterRowCountStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestKeyColumnLetter {
            get {
                return ((string)(this["latestKeyColumnLetter"]));
            }
            set {
                this["latestKeyColumnLetter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestExcelWorksheetIndexesStr {
            get {
                return ((string)(this["latestExcelWorksheetIndexesStr"]));
            }
            set {
                this["latestExcelWorksheetIndexesStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestExcelWorksheetName {
            get {
                return ((string)(this["latestExcelWorksheetName"]));
            }
            set {
                this["latestExcelWorksheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestOperatingRangeAddresses {
            get {
                return ((string)(this["latestOperatingRangeAddresses"]));
            }
            set {
                this["latestOperatingRangeAddresses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestKeyDataColumnName {
            get {
                return ((string)(this["latestKeyDataColumnName"]));
            }
            set {
                this["latestKeyDataColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestNameCardFontName {
            get {
                return ((string)(this["latestNameCardFontName"]));
            }
            set {
                this["latestNameCardFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestBatchProcessWorkbookOption {
            get {
                return ((string)(this["latestBatchProcessWorkbookOption"]));
            }
            set {
                this["latestBatchProcessWorkbookOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string latestSplitWorksheetOption {
            get {
                return ((string)(this["latestSplitWorksheetOption"]));
            }
            set {
                this["latestSplitWorksheetOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\COMIGHT Files")]
        public string savingFolderPath {
            get {
                return ((string)(this["savingFolderPath"]));
            }
            set {
                this["savingFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\pandoc\\pandoc.exe")]
        public string pandocPath {
            get {
                return ((string)(this["pandocPath"]));
            }
            set {
                this["pandocPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("华文中宋")]
        public string cnTitleFontName {
            get {
                return ((string)(this["cnTitleFontName"]));
            }
            set {
                this["cnTitleFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("仿宋")]
        public string cnBodyFontName {
            get {
                return ((string)(this["cnBodyFontName"]));
            }
            set {
                this["cnBodyFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("黑体")]
        public string cnHeading0FontName {
            get {
                return ((string)(this["cnHeading0FontName"]));
            }
            set {
                this["cnHeading0FontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("黑体")]
        public string cnHeading1FontName {
            get {
                return ((string)(this["cnHeading1FontName"]));
            }
            set {
                this["cnHeading1FontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("楷体")]
        public string cnHeading2FontName {
            get {
                return ((string)(this["cnHeading2FontName"]));
            }
            set {
                this["cnHeading2FontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("仿宋")]
        public string cnHeading3_4FontName {
            get {
                return ((string)(this["cnHeading3_4FontName"]));
            }
            set {
                this["cnHeading3_4FontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman")]
        public string enTitleFontName {
            get {
                return ((string)(this["enTitleFontName"]));
            }
            set {
                this["enTitleFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman")]
        public string enBodyFontName {
            get {
                return ((string)(this["enBodyFontName"]));
            }
            set {
                this["enBodyFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial")]
        public string enHeading1FontName {
            get {
                return ((string)(this["enHeading1FontName"]));
            }
            set {
                this["enHeading1FontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman")]
        public string enHeading2FontName {
            get {
                return ((string)(this["enHeading2FontName"]));
            }
            set {
                this["enHeading2FontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman")]
        public string enHeading3_4FontName {
            get {
                return ((string)(this["enHeading3_4FontName"]));
            }
            set {
                this["enHeading3_4FontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public double cnTitleFontSize {
            get {
                return ((double)(this["cnTitleFontSize"]));
            }
            set {
                this["cnTitleFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double cnBodyFontSize {
            get {
                return ((double)(this["cnBodyFontSize"]));
            }
            set {
                this["cnBodyFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double cnHeading0FontSize {
            get {
                return ((double)(this["cnHeading0FontSize"]));
            }
            set {
                this["cnHeading0FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double cnHeading1FontSize {
            get {
                return ((double)(this["cnHeading1FontSize"]));
            }
            set {
                this["cnHeading1FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double cnHeading2FontSize {
            get {
                return ((double)(this["cnHeading2FontSize"]));
            }
            set {
                this["cnHeading2FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double cnHeading3_4FontSize {
            get {
                return ((double)(this["cnHeading3_4FontSize"]));
            }
            set {
                this["cnHeading3_4FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double enTitleFontSize {
            get {
                return ((double)(this["enTitleFontSize"]));
            }
            set {
                this["enTitleFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double enBodyFontSize {
            get {
                return ((double)(this["enBodyFontSize"]));
            }
            set {
                this["enBodyFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public double enHeading1FontSize {
            get {
                return ((double)(this["enHeading1FontSize"]));
            }
            set {
                this["enHeading1FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double enHeading2FontSize {
            get {
                return ((double)(this["enHeading2FontSize"]));
            }
            set {
                this["enHeading2FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double enHeading3_4FontSize {
            get {
                return ((double)(this["enHeading3_4FontSize"]));
            }
            set {
                this["enHeading3_4FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28")]
        public double cnLineSpace {
            get {
                return ((double)(this["cnLineSpace"]));
            }
            set {
                this["cnLineSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public double enLineSpace {
            get {
                return ((double)(this["enLineSpace"]));
            }
            set {
                this["enLineSpace"] = value;
            }
        }
    }
}
